#requires -Version 5.1
<#
.SYNOPSIS
    Installs the screenshot-snippets clipboard watcher to run at login.

.DESCRIPTION
    This script:
      1. Copies screenshot-snippets.ps1 to a stable location under your
         user profile (%USERPROFILE%\.screenshot-snippets).
      2. Creates a hidden VBS launcher in the same directory.
      3. Drops a shortcut in your Windows Startup folder so the watcher
         starts automatically every time you log in.

    Run this once per machine. After installation, sign out and back in
    (or run the VBS manually) to start the watcher.

.PARAMETER OutputDir
    Directory where captured PNGs are saved. Defaults to the system TEMP
    folder. You can also set the SCREENSHOT_SNIPPETS_DIR environment variable.
#>
[CmdletBinding()]
param(
    [string]$OutputDir = $env:SCREENSHOT_SNIPPETS_DIR
)

$ErrorActionPreference = "Stop"

$installDir = Join-Path $env:USERPROFILE ".screenshot-snippets"
$ps1Source = Join-Path $PSScriptRoot "screenshot-snippets.ps1"
$ps1Dest = Join-Path $installDir "screenshot-snippets.ps1"
$vbsDest = Join-Path $installDir "screenshot-snippets.vbs"
$startupFolder = [Environment]::GetFolderPath("Startup")
$shortcutPath = Join-Path $startupFolder "screenshot-snippets.lnk"

if (-not (Test-Path $ps1Source)) {
    Write-Error "screenshot-snippets.ps1 not found next to install.ps1. Make sure you run install.ps1 from the cloned repo directory."
    exit 1
}

if (-not $OutputDir) {
    $OutputDir = $env:TEMP
}

# Ensure output directory exists
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# Create install directory and copy the watcher
New-Item -ItemType Directory -Path $installDir -Force | Out-Null
Copy-Item -Path $ps1Source -Destination $ps1Dest -Force

# Build the VBS launcher with the correct path.
# WindowStyle=0 keeps the PowerShell process hidden (no console flash).
$vbsTemplate = @'
' Hidden launcher for screenshot-snippets.ps1 - no console window appears.
' Generated by install.ps1. Do not edit by hand; re-run install.ps1 instead.

Set objShell = CreateObject("WScript.Shell")
strCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -Sta -File ""{0}"" -OutputDir ""{1}"""
objShell.Run strCmd, 0, False
'@

# VBS only needs embedded quotes escaped; backslashes are literal in strings.
$escapedPs1 = $ps1Dest -replace '"', '""'
$escapedDir = $OutputDir -replace '"', '""'
$vbsContent = $vbsTemplate -f $escapedPs1, $escapedDir
$vbsContent = $vbsContent.TrimEnd()

$vbsContent | Out-File -FilePath $vbsDest -Encoding utf8 -NoNewline -Force

# Create or replace the startup shortcut
if (Test-Path $shortcutPath) {
    Remove-Item $shortcutPath -Force
}

$wshell = New-Object -ComObject WScript.Shell
$shortcut = $wshell.CreateShortcut($shortcutPath)
$shortcut.TargetPath = $vbsDest
$shortcut.WorkingDirectory = $installDir
$shortcut.WindowStyle = 7
$shortcut.Description = "Clipboard image watcher for Windows terminals"
$shortcut.Save()

Write-Output "screenshot-snippets installed successfully."
Write-Output "  Install directory: $installDir"
Write-Output "  Captures saved to: $OutputDir"
Write-Output "  Startup shortcut:  $shortcutPath"
Write-Output ""
Write-Output "Start it now by running:"
Write-Output "  wscript `"$vbsDest`""
Write-Output ""
Write-Output "It will also start automatically the next time you log in."
